# Generated by Django 4.1.7 on 2023-02-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('album', models.TextField()),
                ('artist', models.TextField()),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistSongsXREF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_wins', models.IntegerField(default=0)),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranker_app.playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranker_app.song')),
            ],
        ),
    ]
