# Generated by Django 4.1.7 on 2023-02-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranker_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistSongsXREF',
            new_name='PlaylistSongsWins',
        ),
    ]
