# Generated by Django 4.1.7 on 2023-02-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranker_app', '0002_rename_playlistsongsxref_playlistsongswins'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='owner_id',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
